import type { Zone, Alert, AdminProfile, AdminTask, Route } from '@/types'

export const mockZones: Zone[] = [
  {
    id: 'z1',
    name: 'Food Street',
    status: 'red',
    density_percent: 91,
    capacity: 500,
    current_count: 455,
    lat: 16.4936691,
    lng: 80.4983456,
    radius: 80,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'z2',
    name: 'CB',
    status: 'yellow',
    density_percent: 67,
    capacity: 800,
    current_count: 536,
    lat: 16.4943535,
    lng: 80.4991899,
    radius: 80,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'z3',
    name: 'AB1',
    status: 'green',
    density_percent: 30,
    capacity: 400,
    current_count: 120,
    lat: 16.4957750,
    lng: 80.5004053,
    radius: 80,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'z4',
    name: 'AB2',
    status: 'green',
    density_percent: 22,
    capacity: 300,
    current_count: 66,
    lat: 16.4957371,
    lng: 80.4981280,
    radius: 80,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'z5',
    name: 'Rock Plaza',
    status: 'yellow',
    density_percent: 59,
    capacity: 600,
    current_count: 354,
    lat: 16.4949631,
    lng: 80.4979211,
    radius: 80,
    updated_at: new Date().toISOString(),
  },
]

export const mockAlerts: Alert[] = [
  {
    id: 'a1',
    type: 'stampede_risk',
    zone_id: 'z1',
    zone_name: 'Food Street',
    message: 'Crowd density has exceeded 90%. Risk of stampede. Redirect crowd immediately.',
    severity: 'critical',
    created_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    resolved: false,
  },
  {
    id: 'a2',
    type: 'red_zone',
    zone_id: 'z1',
    zone_name: 'Food Street',
    message: 'Zone classified RED. Restrict further entry.',
    severity: 'high',
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    resolved: false,
  },
  {
    id: 'a3',
    type: 'medical_emergency',
    zone_id: 'z2',
    zone_name: 'CB',
    message: 'Medical emergency reported near fountain. Medical team deployed.',
    severity: 'high',
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    resolved: false,
  },
  {
    id: 'a4',
    type: 'lost_child',
    zone_id: 'z3',
    zone_name: 'AB1',
    message: 'Lost child - Age 7, wearing red shirt. Last seen AB1.',
    severity: 'medium',
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    resolved: false,
  },
]

export const mockAdmins: AdminProfile[] = [
  {
    id: 'adm1',
    name: 'Rajan Sharma',
    email: 'rajan@sas.gov',
    role: 'admin',
    zone_id: 'z1',
    zone_name: 'Food Street',
    gps_lat: 16.4936691,
    gps_lng: 80.4983456,
    online: true,
    tasks_assigned: 24,
    tasks_completed: 21,
    tasks_rejected: 1,
    avg_response_seconds: 42,
  },
  {
    id: 'adm2',
    name: 'Priya Verma',
    email: 'priya@sas.gov',
    role: 'admin',
    zone_id: 'z2',
    zone_name: 'CB',
    gps_lat: 16.4943535,
    gps_lng: 80.4991899,
    online: true,
    tasks_assigned: 18,
    tasks_completed: 17,
    tasks_rejected: 0,
    avg_response_seconds: 28,
  },
  {
    id: 'adm3',
    name: 'Suresh Kumar',
    email: 'suresh@sas.gov',
    role: 'admin',
    zone_id: 'z3',
    zone_name: 'AB1',
    gps_lat: 16.4957750,
    gps_lng: 80.5004053,
    online: false,
    tasks_assigned: 15,
    tasks_completed: 11,
    tasks_rejected: 3,
    avg_response_seconds: 80,
  },
  {
    id: 'adm4',
    name: 'Anjali Singh',
    email: 'anjali@sas.gov',
    role: 'admin',
    zone_id: 'z4',
    zone_name: 'AB2',
    gps_lat: 16.4957371,
    gps_lng: 80.4981280,
    online: true,
    tasks_assigned: 20,
    tasks_completed: 19,
    tasks_rejected: 0,
    avg_response_seconds: 19,
  },
]

export const mockTasks: AdminTask[] = [
  {
    id: 't1',
    instruction: 'Deploy 4 personnel to Food Street immediately. Control crowd flow entering the zone.',
    zone_id: 'z1',
    zone_name: 'Food Street',
    assigned_to: 'adm1',
    assigned_by: 'superadmin',
    status: 'pending',
    created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    responded_at: null,
  },
  {
    id: 't2',
    instruction: 'Open alternate exit route via Rock Plaza side. Guide crowd from CB.',
    zone_id: 'z2',
    zone_name: 'CB',
    assigned_to: 'adm1',
    assigned_by: 'superadmin',
    status: 'accepted',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    responded_at: new Date(Date.now() - 13 * 60 * 1000).toISOString(),
  },
  {
    id: 't3',
    instruction: 'Verify crowd count in AB1 and submit head count report.',
    zone_id: 'z3',
    zone_name: 'AB1',
    assigned_to: 'adm1',
    assigned_by: 'superadmin',
    status: 'completed',
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    responded_at: new Date(Date.now() - 58 * 60 * 1000).toISOString(),
  },
]

export const mockRoutes: Route[] = [
  {
    id: 'r1',
    name: 'Via AB1',
    from_zone: 'Food Street',
    to_zone: 'AB2',
    distance_km: 0.4,
    time_minutes: 6,
    crowd_score: 28,
    route_score: 18,
    safe: true,
  },
  {
    id: 'r2',
    name: 'Via Rock Plaza',
    from_zone: 'Food Street',
    to_zone: 'AB2',
    distance_km: 0.3,
    time_minutes: 5,
    crowd_score: 62,
    route_score: 45,
    safe: false,
  },
  {
    id: 'r3',
    name: 'Via CB',
    from_zone: 'Food Street',
    to_zone: 'AB2',
    distance_km: 0.7,
    time_minutes: 11,
    crowd_score: 70,
    route_score: 58,
    safe: false,
  },
]

export function timeAgo(iso: string): string {
  const diff = Math.floor((Date.now() - new Date(iso).getTime()) / 1000)
  if (diff < 60) return `${diff}s ago`
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`
  return `${Math.floor(diff / 3600)}h ago`
}

export function getPerformanceScore(a: AdminProfile): number {
  return Math.round(
    (a.tasks_completed * 4 + (a.tasks_assigned > 0 ? (a.tasks_completed / a.tasks_assigned) * 20 : 0)) -
    a.tasks_rejected * 3 -
    Math.min(a.avg_response_seconds / 10, 10)
  )
}
